### ISSUE TITLE
User-defined allocation functions

### ISSUE THREAD

**Issue by BlackGoku36** [Arka-Mondal/clibds#2]
In my opinion, this library should provide some way to let user use their own dynamic allocation functions such as malloc, realloc, etc. Because then they have option to not depend on C's stdlib and maybe use some custom allocators.

Eg: 
- https://github.com/floooh/sokol/blob/7373dda48c5e62953cc7ec942da90fc6a25989fa/sokol_gfx.h#L713
- https://github.com/floooh/sokol/blob/7373dda48c5e62953cc7ec942da90fc6a25989fa/sokol_gfx.h#L4762

**Comment by arixsnow** [comment]
Yes, I agree with that. I have planned for that, but for now I am working on the iterators. After that probably I will go for that. If you want to work on the issue (#2), you can go ahead.
